module.exports = {
    GET_ARRAY: 'GET_ARRAY',
    SET_ARRAY: 'SET_ARRAY',
    GET_CHOSEN_CARD: 'GET_CHOSEN_CARD',
    SET_CHOSEN_CARD: 'SET_CHOSEN_CARD',
    SET_OPENED_CARDS: 'SET_OPENED_CARDS',
    GET_OPENED_CARDS: 'GET_OPENED_CARDS',
    GET_GUESSED_CARDS: 'GET_GUESSED_CARDS',
    SET_TEMPORARY_CARDS_OPEN: 'SET_TEMPORARY_CARDS_OPEN'
};